name: build
on:
- push
- workflow_dispatch

jobs:
  build_package:
    runs-on: ubuntu-latest
    name: Run Pester tests
    steps:
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'

    - uses: NuGet/setup-nuget@v1.0.2
      with:
        nuget-version: 5.x

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install GitVersion
      run: |
        dotnet tool install -g GitVersion.Tool --version 5.2.4
        echo "::add-path::/github/home/.dotnet/tools"    
    - name: Run GitVersion
      id: run_gitversion
      run: |
        pwsh -noprofile -c '(dotnet-gitversion | ConvertFrom-Json).psobject.properties | % { echo ("::set-output name={0}::{1}" -f $_.name, $_.value) }'

    - name: Test Build Package
      run: |
        nuget pack ./Endjin.MetaPackage.SpecFlow.nuspec -Version ${{ steps.run_gitversion.outputs.NuGetVersion }}
